CREATE TABLE newspapers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  newspaper_id INTEGER NOT NULL, -- the mysterious extra newspaper id which we never join to but always display
  title TEXT NOT NULL,
  common_title TEXT,
  location TEXT,
  start_year INTEGER,
  end_year INTEGER,
  details TEXT,
  newspaper_type TEXT,
  colony_state TEXT,
  start_date DATE,
  end_date DATE,
  issn TEXT
);
