CREATE TABLE titles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  newspaper_table_id INTEGER REFERENCES newspapers(id),
  span_start DATE, -- the date that the first chapter of the fictional work was published in the newspaper
  span_end DATE, -- the date that the last chapter of the fictional work was published in the newspaper (could be the same as span_start if the work only contains a single 'chapter')
  publication_title TEXT, -- the title of the fictional work as it appears in the newspaper
  attributed_author_name TEXT, -- attribution (author name) as it appears in the publication event (esp paratext).
  common_title TEXT, -- title of the fictional work as it's most commonly represented throughout the database, secondary sources, etc
  author_id INTEGER REFERENCES authors(id), -- the id of the author in the authors table (if known)
  author_of TEXT, -- also referred to as 'signature' in the interface (eg "By the Author of 'The Old Curiosity Shop'")
  additional_info TEXT, -- other info about the author or fictional work supplied in the publication event (eg copyright, translation details, etc)
  inscribed_author_nationality TEXT, -- the nationality of the author as it appears (if it appears) in the publication event (esp paratext)
  inscribed_author_gender TEXT, -- the gender of the author as it appears (if it appears) in the publication event (esp paratext)
  information_source TEXT, -- if available, sources of information about the fictional work (including its publication or attribution)
  length INTEGER, -- either '0' for 'a story serialised over two or more editions of a newspaper'/"Serialised Story", '1' for 'completed in a single edition', or '8' for 'completed in a single edition but comprising 10,000 words or more'
  trove_source TEXT, -- the 'publication source' as identified in the newspaper (eg "From Chambers's"). often NULL.
  also_published TEXT, -- if known, list titles of other periodicals, books, databases, etc where the fictional work is also published. often NULL.
  name_category TEXT, -- attributed, unattributed, unattributed with signature, etc
  curated_dataset BOOLEAN DEFAULT FALSE, -- whether the title is part of the 'curated dataset' (ie the titles that have been manually checked and verified by the project team)
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  added_by INTEGER REFERENCES users(id)
);
