CREATE TABLE authors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    common_name TEXT NOT NULL,
    other_name TEXT,
    gender TEXT,
    nationality TEXT,
    nationality_details TEXT,
    author_details TEXT,
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
